# Generated by Django 4.2.6 on 2023-12-26 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0002_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('bio', models.TextField()),
                ('location', models.TextField()),
                ('sqft', models.IntegerField()),
                ('bed', models.IntegerField()),
                ('bath', models.IntegerField()),
            ],
        ),
    ]
