# Generated by Django 4.2.6 on 2023-12-28 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0004_list1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('rank', models.CharField(max_length=200)),
                ('img', models.ImageField(upload_to='index/img')),
            ],
        ),
    ]
