# Generated by Django 4.2.6 on 2024-01-01 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0005_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('job', models.CharField(max_length=200)),
                ('comment', models.TextField()),
                ('img', models.ImageField(upload_to='index/img')),
            ],
        ),
    ]
