# Generated by Django 4.2.6 on 2024-01-03 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0008_team_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='slug',
            field=models.SlugField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
